### ISSUE TITLE
Migration of Play aggregation plugin

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#12]
Existing code in Gradle core: https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayPlugin.java

**Comment by pioterj** [comment]
What's left in this epic?

**Comment by bmuschko** [comment]
@pioterj The reason I left this unresolved:

- Users mainly apply this plugin in their build scripts.
- The application plugin is automatically applied by this plugin.
- The application plugin (and its epic) still has to address the integration testing for running the application and continuous build.
- So this is more a dependency on the Play application plugin but I'd be happy to just close this epic.

@big-guy Is there a specific reason why we have a Play application plugin and a Play aggregation plugin? Or asked differently: Would users ever apply the Play application plugin instead of the Play aggregation plugin.
