### ISSUE TITLE
Play Routes plugin: Custom task type should live in plugin

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#18]
- Move the custom task type ([`RoutesCompile`](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/RoutesCompile.java)) into external plugin implementation
- Instantiates the local custom task type instead of the one in Gradle core
- Make potential changes to implementation to enable lazy evaluation (`Provider` types)

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/blob/master/src/main/java/com/lightbend/play/tasks/RoutesCompile.java

**Comment by big-guy** [comment]
Same thing about unused forkOptions

**Comment by bmuschko** [comment]
Removed fork options: https://github.com/gradle/play/commit/ecf2b9e1ab5a2b49686017162bc78c1760299fe1
