### ISSUE TITLE
Set up CI for project on Travis CI

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#2]
- Provide a Travis CI configuration file
- Enable project on Travis CI
- The plugin source code can be compiled, all tests can be run
- Add build badge to `README` file of project

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/blob/master/.travis.yml
- https://travis-ci.org/gradle/play
- https://github.com/gradle/play/blob/master/README.adoc

**Comment by big-guy** [comment]
I think Linux is good enough
