### ISSUE TITLE
Play JavaScript plugin: Custom task type should live in plugin

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#22]
- Move the custom task type ([`JavaScriptMinify`](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/JavaScriptMinify.java)) into external plugin implementation
- Instantiates the local custom task type instead of the one in Gradle core
- Make potential changes to implementation to enable lazy evaluation (`Provider` types)

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/blob/master/src/main/java/com/lightbend/play/tasks/JavaScriptMinify.java

**Comment by big-guy** [comment]
same thing about forkOptions and is `SimpleStaleClassCleaner` necessary?

**Comment by bmuschko** [comment]
The `SimpleStaleClassCleaner` was necessary. Some tests were failing without its use:

`CoffeeScriptCompileIntegrationTest. cleans removed source file on compile`
`JavaScriptMinifyIntegrationTest. cleans removed source file on minify`

Alternatively, we can remove the tests.

Removed fork options: https://github.com/gradle/play/commit/ecf2b9e1ab5a2b49686017162bc78c1760299fe1
