### ISSUE TITLE
Play application plugin: Should expose a DSL for configuring the Play platform

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#29]
- Expose DSL via extension
- Extension fields use `Provider` types
- Can configure Play version, Scala version and Java version
- Captures values are used to configure Play application

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/tree/master/src/main/java/com/lightbend/play/extensions

**Comment by big-guy** [comment]
lgtm, other than #53
