### ISSUE TITLE
Externalize existing documentation page

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#42]
- Externalize source code snippets
- Import source code snippets in docs
- Add ability to generate HTML from it via Asciidoctor
- Change documentation to reflect different plugin behavior

**Comment by pioterj** [comment]
I was thinking to use GitHub Pages for this. We can store the sources of the documentation in this repository directly. See https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch 

cc @eriwen 

What do you mean by

> Change documentation to reflect different plugin behavior

**Comment by bmuschko** [comment]
> I was thinking to use GitHub Pages for this.
That was the plan. It's also what I do for all of my open source plugins.

> Change documentation to reflect different plugin behavior
For example:
- Any change to the DSL that needed to happen because we are not using the software model anymore.
- Removal of plugins that existed before (like the CoffeeScript plugin).
- Any other difference in behavior from how the plugin worked before e.g. that you cannot add custom source sets for Twirl (explicitly feature of the software model).

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/blob/master/buildSrc/src/main/kotlin/com/playframework/gradle/UserGuidePlugin.kt
- https://github.com/gradle/play/tree/master/src/docs
