### ISSUE TITLE
Document developer requirements and how to import

### ISSUE THREAD

**Issue by big-guy** [gradle/play#51]
Min Gradle version, min Java version, min IDE version and any special IDE configuration options.

A user should be able to run tests/integration tests out of the box or there should be documented steps for what must be done first (e.g., build on the command-line first)

**Comment by bmuschko** [comment]
https://github.com/gradle/play/commit/d36894573375b5cda720fc5f1ceb987131970b17

**Comment by big-guy** [comment]
Thanks! a few comments...

- I think JDK9 doesn't work out of the box because of the version of Scala used (2.11).  I use only JDK8
- Integration tests didn't work for me out of the box.  I had to run a build first on the command-line so all of the TestKit metadata was generated.  Are you delegating test execution to Gradle? I couldn't get this to work at all.
- We want to suggest IntelliJ 2018.3+ since that fixes problems with Kotlin DSL

**Comment by bmuschko** [comment]
> I think JDK9 doesn't work out of the box because of the version of Scala used (2.11). I use only JDK8

I can change that.

> Integration tests didn't work for me out of the box. I had to run a build first on the command-line so all of the TestKit metadata was generated. Are you delegating test execution to Gradle? I couldn't get this to work at all.

I guess you mean executing integration tests from the IDE? That's ["normal" behavior of TestKit](https://guides.gradle.org/testing-gradle-plugins/#ide_integration). You'll have to delegate to the build.

> We want to suggest IntelliJ 2018.3+ since that fixes problems with Kotlin DSL

Feel free to change. I used 2018.2 here as a minimum version as it works without issues.
