### ISSUE TITLE
Play Twirl plugin: Custom task type should live in plugin

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#6]
- Move the custom task type ([`TwirlCompile`](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/TwirlCompile.java)) into external plugin implementation
- Instantiates the local custom task type instead of the one in Gradle core
- Make potential changes to implementation to enable lazy evaluation (`Provider` types)

**Comment by bmuschko** [comment]
Implementation:

- https://github.com/gradle/play/blob/master/src/main/java/com/lightbend/play/tasks/TwirlCompile.java
- https://github.com/gradle/play/blob/master/src/main/java/com/lightbend/play/tasks/TwirlCompileRunnable.java

**Comment by bmuschko** [comment]
@big-guy Find my answers to your comments here.

> I would say that the new tasks doesn't need to be as clever as the old ones.  so cutting out incrementalness makes it easier to do

OK, I didn't add it back. For now I ignored the relevant integration tests that handle incrementalness.

> The detachedConfiguration stuff could go away and just use a named configuration added by the twirl compiler with a default dependency

Done, I created the named configuration in the plugin and passed along the classpath as `FileCollection`.

> The task has some extra properties/methods that don't make sense now (related to the tool chain)

From the existing integration tests it looks like all of them are used right now. We can thin them out later if you think something is not needed.

> I would experiment/look at trying to create the compiler inside the runnable

To create the compiler you need the `PlayPlatform`. At the moment the class is not serializable yet so you can't do it in the `Runnable` at the moment. We can revisit as soon as we move that class into the plugin.

> because the gradle/gradle build tries to force you to use Java 6 for some reason, the runnable deleteOutputs is more complicated than it needs to be.

OK

**Comment by big-guy** [comment]
It looks like forkOptions aren't necessary anymore or we should be using them to configure the worker instead?

**Comment by bmuschko** [comment]
My first thinking was to just pass them to `WorkerConfiguration` but it doesn't accept a `BaseForkOptions`. Let's remove it for now. Hopefully, users won't have to tweak those options and it "just works". You might have seen that I needed to pass `-XX:MaxMetaspaceSize=256m` to the worker though. Initially, it was just failing with an error message.

**Comment by bmuschko** [comment]
Removed fork options: https://github.com/gradle/play/commit/ecf2b9e1ab5a2b49686017162bc78c1760299fe1
