### ISSUE TITLE
Packages and plugin IDs should reflect the Play framework hosting domain

### ISSUE THREAD

**Issue by bmuschko** [gradle/play#60]
The URL of the Play framework is https://www.playframework.com/. Packages and plugin IDs should reflect that: `com.playframework` will be used.

**Comment by pioterj** [comment]
Sounds good to me. I've sent an email to Lightbend regarding usage of `com.playframework`.

**Comment by bmuschko** [comment]
I made the change to get it out of the way.

**Comment by big-guy** [comment]
This LGTM, do we just need to block this until we hear back?

**Comment by bmuschko** [comment]
// TODO: Will require adjusting the publishing information in `build.gradle.kts`.

```
pluginBundle {
    website = "https://www.playframework.com/"
    vcsUrl = "https://github.com/gradle/play"
}
```

**Comment by bmuschko** [comment]
We decided to go with `org.gradle`.

**Comment by bmuschko** [comment]
@pioterj I was looking at the proposed prefix a little closer. I don't think we'll be able to use it...at least for the plugin ID. The reason is that you can omit `org.gradle` when applying standard Gradle plugins. 

For example:

```
plugins {
    id 'play'
}
```

and

```
plugins {
    id 'org.gradle.play'
}
```

are pointing to the same plugin. If we'd go with the proposed plugin ID then we'd have a naming conflict. We'll need to come up with a (maybe just slightly) different solution. Potentially something like `org.gradle.community.play` could work.

**Comment by bmuschko** [comment]
It was decided to go with `org.gradle.playframework` to ensure a unique plugin ID pattern.

**Comment by bmuschko** [comment]
Implementation: https://github.com/gradle/play/commit/423796bbc15d278fc8710331e48de1c8287ddb06
